### ISSUE TITLE
[BUG] MakeDirectory GRPC Call throws null pointer exception

### ISSUE THREAD

**Issue by gamebot770** [HootFS/hootfs#21]
On making a MakeDirectory request through NestDash, hootfs crashes with the following: 

Arguments in call:

```
session_id = "1"
dir_id =UUID(value=UUID('3838a49d-323f-4873-98aa-e62e518c8939').bytes)
dir_name = "TEST_DIRECTORY_1"
channel = grpc.insecure_channel('localhost:50060') 

```

```

panic: assignment to entry in nil map

goroutine 269 [running]:
github.com/hootfs/hootfs/src/core/file_storage.(*VirtualFileManager).CreateNewDirectory(0xc0001ae720, {0xc00011e200, 0x10}, {0x38, 0x38, 0xa4, 0x9d, 0x32, 0x3f, 0x48, ...})
	/Users/brandonstanley/My Drive/Rice University/Semester 7/COMP 413/HootFS/hootfs/src/core/file_storage/virtual_file_manager.go:52 +0x11a
github.com/hootfs/hootfs/src/core/hootfs.(*HootFsServer).MakeDirectory(0xc000098500, {0xc00059a410, 0x10ed346}, 0xc00059a410)
	/Users/brandonstanley/My Drive/Rice University/Semester 7/COMP 413/HootFS/hootfs/src/core/hootfs/head_node.go:165 +0xae
github.com/hootfs/hootfs/protos._HootFsService_MakeDirectory_Handler({0x1437680, 0xc000098500}, {0x14f6680, 0xc00020ab70}, 0xc00068e3c0, 0x0)
	/Users/brandonstanley/My Drive/Rice University/Semester 7/COMP 413/HootFS/hootfs/protos/head_grpc.pb.go:179 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f1500, {0x14fdeb8, 0xc0000f2180}, 0xc0000b8240, 0xc0001ae8a0, 0x17e8998, 0x0)
	/Users/brandonstanley/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0000f1500, {0x14fdeb8, 0xc0000f2180}, 0xc0000b8240, 0x0)
	/Users/brandonstanley/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/brandonstanley/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/brandonstanley/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:921 +0x294
exit status 2
```

**Comment by josh8551021** [comment]
I believe the issue spawns from the fact that we are attempting to access a directory ID that does not exist in the map as if it does exist. #23 should fix this, as an existence check was added to the `MakeDirectory()` method (among others) before attempting to access a potentially nonexistent `VirtualDirectory` object.

**Comment by gamebot770** [comment]
I am getting back the expected error:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Parent directory does not exist"
	debug_error_string = "{"created":"@1637556051.611251000","description":"Error received from peer ipv6:[::1]:50060","file":"src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"Parent directory does not exist","grpc_status":2}"
```
However, I cannot make any subsequent gRPC requests to the backend. I end up getting back:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1637556101.251036000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1637556101.251035000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
```

No error messages on the server side

**Comment by gamebot770** [comment]
To replicate, I have also added in instructions on setting up NestDash and running tests in the NestDash repo. Let me know if you have any questions

**Comment by josh8551021** [comment]
PR #26 should fix the unavailable status code error. However, it is still not very clear to me that the `InactiveRpcError` should be thrown in all cases. I should soon have an initialization PR up that allows us to test this behavior under conditions in which the RPC returns a passing response.
